# Generated by Django 5.1.2 on 2024-10-09 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiktaktoe', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='field',
            field=models.CharField(default='000000000', max_length=9),
        ),
        migrations.AddField(
            model_name='game',
            name='start_player',
            field=models.CharField(default='-1', max_length=2),
        ),
    ]
