# Generated by Django 5.1.2 on 2024-10-09 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiktaktoe', '0002_game_field_game_start_player'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='field',
            field=models.IntegerField(default=[0, 0, 0, 0, 0, 0, 0, 0, 0]),
        ),
    ]
